name: Update domain-filter.yml

on:
  schedule:
    - cron:  '0 1 */2 * *' # update setiap 2 hari sekali
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Show python version
      run: python3 --version
    - name: Run a script
      run: python3 get_update-filters.py
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Automatic update-filter.txt"
    - name: Push changes
      run: |
        git push -u origin main
